# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

sudo: required

dist: trusty

cache: packages

env:
  - GRIB_API_VERSION=1.20.0

warnings_are_errors: true

addons:
  apt:
    packages:
      - libproj-dev
      - libopenjpeg-dev
      - libjasper-dev
      - libpng-dev
      - zlib1g-dev

before_install:
  - cd $HOME
  - echo Staging dependency files to $(pwd)
  - curl -o grib_api-${GRIB_API_VERSION}-Source.tar.gz https://software.ecmwf.int/wiki/download/attachments/3473437/grib_api-${GRIB_API_VERSION}-Source.tar.gz?api=v2
  - tar -xzf grib_api-${GRIB_API_VERSION}-Source.tar.gz
  - cd grib_api-${GRIB_API_VERSION}-Source
  - mkdir build && cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DENABLE_NETCDF=OFF -DENABLE_JPG=ON -DENABLE_PNG=ON -DENABLE_PYTHON=OFF -DENABLE_FORTRAN=OFF -DENABLE_EXAMPLES=OFF
  - make && sudo make install
  - cd $TRAVIS_BUILD_DIR
