# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

cache: 
  packages: true

addons:
  apt:
    packages:
      - libproj-dev
      - libopenjp2-7-dev
      - libpng-dev
      - zlib1g-dev
      - libaec-dev
  homebrew:
    packages:
      - openjpeg@2.3.1

r_github_packages:
  - jimhester/covr

env:
  global:
    - MAKEFLAGS="-j 2"

matrix:
  include:
    - env: ECCODES_VERSION=2.19.1
      sudo: required
      os: linux
      dist: focal
      r_check_args: --as-cran
      before_install:
        - ./install_eccodes.sh
    - env:
      - ECCODES_VERSION=2.19.1
      - OPENJPEG_INCLUDE_DIR=/usr/local/include/openjpeg-2.3
      sudo: required
      os: osx
      r_check_args: --as-cran
      before_install:
        - ./install_eccodes.sh

after_success:
  - Rscript -e 'covr::codecov()'

warnings_are_errors: true

notifications:
  email:
    on_success: change
    on_failure: change