# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

sudo: required

dist: trusty

cache: packages

warnings_are_errors: true

addons:
  apt:
    packages:
      - libproj-dev
      - libopenjpeg-dev
      - libjasper-dev
      - libpng-dev
      - zlib1g-dev

env:
  global:
    - MAKEFLAGS="j -2"

matrix:
  include:
    - env: GRIB_API_VERSION=1.20.0
      r_check_args: --as-cran --install-args="--configure-args='--with-grib-api'"
      before_install: ./install_grib_api.sh
    - env: ECCODES_VERSION=2.1.0
      r_check_args: --as-cran
      before_install: ./install_eccodes.sh