# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
r_build_args: --with-grib-api
addons:
  apt:
    packages:
      - libproj-dev
      - libgrib-api-dev
